PREPARED_PATH = 'static/data/prepared'
ORIGIN_DATA_PATH_CSV = 'static/data/sensors/csv/'
ORIGIN_DATA_PATH_XLS = 'static/data/sensors/xls/'
ALL_MEASURE_FILENAME = 'all.csv'
POINTS_VALUES_FILENAME = 'values.csv'
