# Generated by Django 3.2.2 on 2021-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_disabilityrequirements_disabilityrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='characteristics',
            field=models.ManyToManyField(blank=True, null=True, to='db.DisabilityRequirement', verbose_name='Характеристики места'),
        ),
    ]
