# Generated by Django 3.2.2 on 2021-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210916_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilitytype',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, to='db.DisabilityRequirement', verbose_name='Доступные условия'),
        ),
    ]
