# Generated by Django 3.2.2 on 2021-09-21 12:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_disabilitytype_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disabilityrequirement',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.RemoveField(
            model_name='disabilitytype',
            name='requirements',
        ),
        migrations.AddField(
            model_name='disabilitytype',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='point',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='point',
            name='characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
