# Generated by Django 3.2.2 on 2021-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20210921_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisabilityType',
            new_name='PeopleType',
        ),
    ]
