# Generated by Django 3.2.2 on 2021-09-21 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_rename_disabilitytype_peopletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopletype',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
