# Generated by Django 3.2.2 on 2021-09-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20210921_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время измерения')),
                ('temp', models.FloatField(verbose_name='Температура')),
                ('wet', models.FloatField(verbose_name='Влажность')),
                ('CO2', models.FloatField(verbose_name='Содержания CO2')),
                ('LOS', models.FloatField(verbose_name='Значение ЛОС')),
                ('dust_pm_1', models.FloatField(verbose_name='Значение пыли pm 1.0')),
                ('dust_pm_2_5', models.FloatField(verbose_name='Значение пыли pm 2.5')),
                ('dust_pm_10', models.FloatField(verbose_name='Значение пыли pm 10')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('AQI', models.FloatField(verbose_name='Значение AQI')),
                ('formaldehyde', models.FloatField(verbose_name='Формальдегид')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
        migrations.DeleteModel(
            name='DisabilityRequirement',
        ),
        migrations.DeleteModel(
            name='PeopleType',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
