# Generated by Django 3.2.2 on 2021-09-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210925_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
    ]
