# Generated by Django 3.2.2 on 2021-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20210925_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='AQI',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение AQI'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='CO2',
            field=models.FloatField(blank=True, null=True, verbose_name='Содержания CO2'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='LOS',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение ЛОС'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dust_pm_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение пыли pm 1.0'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dust_pm_10',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение пыли pm 10'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dust_pm_2_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение пыли pm 2.5'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='formaldehyde',
            field=models.FloatField(blank=True, null=True, verbose_name='Формальдегид'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='wet',
            field=models.FloatField(blank=True, null=True, verbose_name='Влажность'),
        ),
    ]
